version: '3.8'
services:
  eurekaserver:
    build: ./Eurekaserver
    ports:
      - "8761:8761"

  gateway:
    build: ./Gateway
    ports:
      - "8080:8080"
    depends_on:
      - eurekaserver

  meteo-service:
    build: ./meteo-service
    ports:
      - "8083:8083"
    depends_on:
      - eurekaserver

  notification-service:
    build: ./notification-service
    ports:
      - "8082:8082"
    depends_on:
      - eurekaserver

  user-service:
    build: ./user-service
    ports:
      - "8081:8081"
    depends_on:
      - eurekaserver
